apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-graph-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-graph-api
  template:
    metadata:
      labels:
        app: asset-graph-api
    spec:
      containers:
      - name: asset-graph-api
        image: gcr.io/check4coin/asset-graph-api:master
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URL
          value: 'mongodb://mongo:27017'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: asset-graph-api
spec:
  selector:
    app: asset-graph-api
  ports:
  - name: http
    port: 80
    targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: asset-graph-api-public
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Headers:Authorization,Content-Type"
spec:
  rules:
  - host: api.check4coin.com
    http:
      paths:
      - path: /asset-graph/v1
        backend:
          serviceName: asset-graph-api
          servicePort: http
