const prices = [{
    Name : "EUR-LTL",
    Last : 0.3,
    BaseVolume : 50,
    ReceivedOn : new Date(),
    MarketCurrency : "LTL",
    BaseCurrency : "EUR",
    Exchange : "Exchange 1",
    Ask : 0.31,
    Bid : 0.29,
    WriteDate : new Date(),
}, {
    Name : "USD-LTL",
    Last : 0.33,
    BaseVolume : 5000,
    ReceivedOn : new Date(),
    MarketCurrency : "LTL",
    BaseCurrency : "USD",
    Exchange : "Exchange 2",
    Ask : 0.34,
    Bid : 0.32,
    WriteDate : new Date(),
}, {
    Name : "USD-EUR",
    Last : 0.88,
    BaseVolume : 50,
    ReceivedOn : new Date(),
    MarketCurrency : "EUR",
    BaseCurrency : "USD",
    Exchange : "Exchange 3",
    Ask : 0.89,
    Bid : 0.87,
    WriteDate : new Date(),
}, {
    Name : "JPY-LTL",
    Last : 1,
    BaseVolume : 50,
    ReceivedOn : new Date(),
    MarketCurrency : "LTL",
    BaseCurrency : "JPY",
    Exchange : "Exchange 5",
    Ask : 1.1,
    Bid : 0.9,
    WriteDate : new Date(),
},

];

export default {prices};
